### ISSUE TITLE
Why is my application redirecting to the wrong Authorize endpoint?

### ISSUE THREAD

**Issue by g33kidd** [schwarz/ueberauth_discord#2]
I can see you have `/api/oauth2/authorize` as a default and all the endpoints are correct, but my application is redirecting to `oauth2/authorize. I can't seem to figure out why it would be doing that. I'm not overriding any of the oauth2 stuff and my client/secret is correct.

Any ideas?

**Comment by tielur** [comment]
I started looking at this tonight and I'm getting this same problem.

**Comment by schwarz** [comment]
It does seem like Discord is redirecting (302) /api/oauth2/authorize to /oauth2/authorize, but the docs only state /api/oauth2/authorize.

What problems does this cause for you? Using /oauth2/authorize directly would work, but this behavior might change serverside at any point.

**Comment by tielur** [comment]
I had an issue that I thought was related to this but it wasn't. I was getting an "unknown error" that was related to not adding my redirect uri to my discord app. I think adding that step in the README might help clear that up.

**Comment by schwarz** [comment]
I've added a note on that to the installation instructions!
