### ISSUE TITLE
Changing redirect uri

### ISSUE THREAD

**Issue by sean-clayton** [schwarz/ueberauth_discord#3]
The current redirect URI sent after visiting `/auth/discord` always begins with `http`, but my site is over https so I need it to be `https`. Unfortunately, this causes discord auth to fail because the redirect URI I have set up doesn't match. Is there a way to change the redirect URI?

Doing it like this has no effect:

```elixir
config :ueberauth, Ueberauth.Strategy.Discord.OAuth,
  client_id: System.get_env("DISCORD_CLIENT_ID"),
  client_secret: System.get_env("DISCORD_CLIENT_SECRET"),
  redirect_uri: "https://example.com"
```

**Comment by schwarz** [comment]
Sorry for the late response. Please see ueberauth/ueberauth#18 for how to configure the redirect URI.

It could look something like this:

    config :ueberauth, Ueberauth,
      providers: [
        discord: {Ueberauth.Strategy.Discord, [
          callback_url: "https://example.com"
        ]}
      ]

**Comment by sean-clayton** [comment]
That worked for me! Thanks @schwarz!
