### ISSUE TITLE
Passing additional params to authorize

### ISSUE THREAD

**Issue by tielur** [schwarz/ueberauth_discord#4]
Discord recently added a new `prompt` parameter for the authorization URL that allows you to skip re-approval if the user is already authorized.

How would I go about adding that to my application. Does it require a change to this strategy?

**Comment by tielur** [comment]
Sorry forgot to add more details:
Here's the PR https://github.com/discordapp/discord-api-docs/issues/264 with more details and the [commit](https://github.com/discordapp/discord-api-docs/commit/e6d6cbee9216766ee97f230c0e47a3ba93bb850a) related to the changes

**Comment by tielur** [comment]
Looks like the authorize querystring can contain a `prompt` parameter now.

**Comment by schwarz** [comment]
Apologies for the delay, I've added support for the prompt parameter settable through query string as well as config!

**Comment by tielur** [comment]
Awesome thanks @schwarz
